import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Boxes, Check, ChevronLeft, ChevronRight, Info, MapPin, ShieldCheck, Target } from "lucide-react";
import { useState } from "react";
import { AppShell, DemoBadge, Disclaimer, VerificationGate } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export const Route = createFileRoute("/cadastrar")({ head: () => ({ meta: [{ title: "Cadastrar ativo — CircularIA" }, { name: "description", content: "Cadastre uma bateria ou componente para analisar oportunidades circulares." }, { property: "og:title", content: "Cadastrar ativo — CircularIA" }, { property: "og:description", content: "Fluxo demonstrativo de cadastro de baterias e componentes." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Register });
const assetTypes = ["Pack de bateria", "Módulo de bateria", "Célula", "BMS", "Inversor", "Conversor DC/DC", "Carregador embarcado", "Unidade de controle eletrônico", "Componentes de eletrônica de potência", "Motor elétrico", "Componentes do sistema de recarga", "Cabos e conectores de alta tensão", "Sensores e módulos eletrônicos", "Outro"];
const steps = [["Identificação", Boxes], ["Dados técnicos", Boxes], ["Localização", MapPin], ["Objetivo", Target]] as const;
function Register() {
  const [step, setStep] = useState(0); const [assetType, setAssetType] = useState("Pack de bateria"); const navigate = useNavigate(); const current = steps[step] ?? steps[0]; const isBattery = ["Pack de bateria", "Módulo de bateria", "Célula"].includes(assetType);
  return <AppShell title="Cadastrar ativo" subtitle="Cadastre o ativo em etapas. A localização precisa permanece protegida até o fechamento.">
    <VerificationGate><div className="mb-6 flex items-center gap-3 rounded-lg border border-primary/25 bg-accent/50 p-4 text-sm"><ShieldCheck className="size-5 text-primary" /><span><strong>Empresa verificada.</strong> Cadastro de anúncios liberado.</span><DemoBadge /></div></VerificationGate>
    <div className="mb-7 grid grid-cols-4 overflow-hidden rounded-lg border border-border bg-card">{steps.map(([t, I], i) => { const Icon = I; return <Button key={t} variant="ghost" onClick={() => setStep(i)} className={`h-20 rounded-none border-r border-border px-2 text-xs last:border-r-0 md:text-sm ${i === step ? "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground" : i < step ? "bg-accent text-accent-foreground" : "text-muted-foreground"}`}>{i < step ? <Check className="size-4" /> : <Icon className="size-4" />}<span className="hidden sm:inline">{t}</span><span className="sm:hidden">{i + 1}</span></Button>; })}</div>
    <div className="mx-auto max-w-4xl rounded-lg border border-border bg-card p-5 md:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-primary">Etapa {step + 1} de 4</p><h2 className="mt-2 text-xl font-bold">{current[0]}</h2></div><DemoBadge /></div><div className="mt-7">
      {step === 0 && <><label><span className="mb-2 block text-sm font-semibold">Tipo de ativo</span><select value={assetType} onChange={(event) => setAssetType(event.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{assetTypes.map((type) => <option key={type}>{type}</option>)}</select></label><div className="mt-5"><Fields fields={["Fabricante", "Modelo", "Identificador interno", "Ano", "Quantidade", "Estado/condição", "Origem", "Documentação técnica disponível"]} values={{ Fabricante: "Fabricante demonstrativo", Modelo: isBattery ? "Pack NMC 72" : "Modelo demonstrativo", "Identificador interno": isBattery ? "BAT-00192" : "CMP-00512", Ano: "2020", Quantidade: "8", "Estado/condição": "Retirado de operação", Origem: "Frota própria", "Documentação técnica disponível": "Sim — documento anexado" }} options={{ "Estado/condição": ["Em operação", "Retirado de operação", "Funcional", "Recondicionado", "Requer avaliação externa"], "Documentação técnica disponível": ["Sim — documento anexado", "Sim — a enviar", "Não disponível"] }} /></div></>}
      {step === 1 && (isBattery ? <><Fields fields={["Química", "Capacidade", "Tensão", "Peso", "SoH, quando disponível", "Origem do SoH", "Nível de confiabilidade registrado"]} values={{ Química: "NMC", Capacidade: "72 kWh", Tensão: "400 V", Peso: "480 kg", "SoH, quando disponível": "78%", "Origem do SoH": "Diagnóstico externo", "Nível de confiabilidade registrado": "Alto — documento anexado" }} options={{ Química: ["LFP", "NMC", "NCA", "Outra"], "Origem do SoH": ["Informado pelo proprietário", "BMS", "Diagnóstico externo", "Documentação técnica"], "Nível de confiabilidade registrado": ["Baixo — autodeclarado", "Médio — BMS ou documentação", "Alto — diagnóstico externo"] }} /><div className="mt-5 flex gap-3 rounded-md border border-primary/25 bg-accent/50 p-4 text-xs text-muted-foreground"><Info className="size-5 shrink-0 text-primary" /><span><strong className="text-foreground">Sobre o SoH:</strong> a origem e a confiabilidade são registradas. A CircularIA não mede fisicamente o SoH; inspeções e ensaios permanecem com agentes habilitados.</span></div></> : <Fields fields={["Categoria", "Tensão nominal", "Potência nominal, quando aplicável", "Código/part number", "Compatibilidade conhecida", "Condição funcional", "Testado / não testado", "Laudo ou diagnóstico disponível", "Observações técnicas"]} values={{ Categoria: "Eletrônica de potência", "Tensão nominal": "400 V", "Potência nominal, quando aplicável": "150 kW", "Código/part number": "CMP-400-150", "Compatibilidade conhecida": "Plataformas de 350–450 V", "Condição funcional": "Funcional", "Testado / não testado": "Testado", "Laudo ou diagnóstico disponível": "Sim — laudo anexado", "Observações técnicas": "Sem avarias aparentes" }} options={{ Categoria: ["Eletrônica de potência", "Controle eletrônico", "Sistema de recarga", "Propulsão", "Sensores e módulos"], "Condição funcional": ["Funcional", "Recondicionado", "Requer reparo", "Condição desconhecida"], "Testado / não testado": ["Testado", "Não testado"], "Laudo ou diagnóstico disponível": ["Sim — laudo anexado", "Sim — a enviar", "Não disponível"] }} />)}
      {step === 2 && <><Fields fields={["Estado", "Cidade/região aproximada", "Localização de retirada"]} values={{ Estado: "SP", "Cidade/região aproximada": "São Paulo (região aproximada)", "Localização de retirada": "Disponível após o fechamento" }} options={{ Estado: ["SP", "MG", "RJ", "PR", "RS", "GO", "PE", "AM"] }} /><p className="mt-4 text-xs text-muted-foreground">O endereço completo e a localização precisa não serão mostrados antes do fechamento protegido da negociação.</p></>}
      {step === 3 && <Options />}
    </div><div className="mt-8"><Disclaimer /></div><div className="mt-7 flex justify-between"><Button variant="outline" disabled={step === 0} onClick={() => setStep((s) => s - 1)}><ChevronLeft />Voltar</Button>{step < 3 ? <Button onClick={() => setStep((s) => s + 1)}>Continuar<ChevronRight /></Button> : <Button onClick={() => navigate({ to: "/matches" })}>Analisar oportunidades<ChevronRight /></Button>}</div></div>
  </AppShell>;
}
function Fields({ fields, options = {}, values = {} }: { fields: string[]; options?: Record<string, string[]>; values?: Record<string, string> }) { return <div className="grid gap-5 md:grid-cols-2">{fields.map((f) => <label key={f}><span className="mb-2 block text-sm font-semibold">{f}</span>{options[f] ? <select defaultValue={values[f]} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{options[f].map((x) => <option key={x}>{x}</option>)}</select> : <Input defaultValue={values[f]} placeholder="Informe o dado disponível" />}</label>)}</div>; }
function Options() { const [selected, setSelected] = useState("Aberto à recomendação da plataforma"); return <div className="grid gap-3">{["Reutilização", "Segunda vida", "Remanufatura", "Recondicionamento", "Reparo", "Aproveitamento de componentes", "Reciclagem", "Aberto à recomendação da plataforma"].map((x) => <Button key={x} variant="outline" onClick={() => setSelected(x)} className={`h-auto justify-start p-4 text-left ${selected === x ? "border-primary bg-accent" : ""}`}><span className={`size-4 rounded-full border-4 ${selected === x ? "border-primary" : "border-input"}`} />{x}</Button>)}</div>; }
