import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Battery, Check, ChevronLeft, ChevronRight, Info, MapPin, ShieldCheck, Target } from "lucide-react";
import { useState } from "react";
import { AppShell, DemoBadge, Disclaimer, VerificationGate } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export const Route = createFileRoute("/cadastrar")({ head: () => ({ meta: [{ title: "Cadastrar ativo — CircularIA" }, { name: "description", content: "Cadastre uma bateria ou componente para analisar oportunidades circulares." }, { property: "og:title", content: "Cadastrar ativo — CircularIA" }, { property: "og:description", content: "Fluxo demonstrativo de cadastro de baterias e componentes." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Register });
const steps = [["Identificação", Battery], ["Dados técnicos", Battery], ["Localização", MapPin], ["Objetivo", Target]] as const;
function Register() {
  const [step, setStep] = useState(0); const navigate = useNavigate(); const current = steps[step] ?? steps[0];
  return <AppShell title="Cadastrar ativo" subtitle="Cadastre o ativo em etapas. A localização precisa permanece protegida até o fechamento.">
    <VerificationGate><div className="mb-6 flex items-center gap-3 rounded-lg border border-primary/25 bg-accent/50 p-4 text-sm"><ShieldCheck className="size-5 text-primary" /><span><strong>Empresa verificada.</strong> Cadastro de anúncios liberado.</span><DemoBadge /></div></VerificationGate>
    <div className="mb-7 grid grid-cols-4 overflow-hidden rounded-lg border border-border bg-card">{steps.map(([t, I], i) => { const Icon = I; return <Button key={t} variant="ghost" onClick={() => setStep(i)} className={`h-20 rounded-none border-r border-border px-2 text-xs last:border-r-0 md:text-sm ${i === step ? "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground" : i < step ? "bg-accent text-accent-foreground" : "text-muted-foreground"}`}>{i < step ? <Check className="size-4" /> : <Icon className="size-4" />}<span className="hidden sm:inline">{t}</span><span className="sm:hidden">{i + 1}</span></Button>; })}</div>
    <div className="mx-auto max-w-4xl rounded-lg border border-border bg-card p-5 md:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-primary">Etapa {step + 1} de 4</p><h2 className="mt-2 text-xl font-bold">{current[0]}</h2></div><DemoBadge /></div><div className="mt-7">
      {step === 0 && <Fields fields={["Tipo de ativo", "Fabricante", "Modelo", "Identificador interno", "Ano", "Quantidade"]} values={{ "Tipo de ativo": "Bateria completa", Fabricante: "Fabricante demonstrativo", Modelo: "Pack NMC 72", "Identificador interno": "BAT-00192", Ano: "2020", Quantidade: "8" }} options={{ "Tipo de ativo": ["Bateria completa", "Módulo", "Célula", "Outro componente"] }} />}
      {step === 1 && <><Fields fields={["Química", "Capacidade", "Tensão", "Peso", "Condição conhecida", "SoH, quando disponível", "Origem do dado de SoH", "Nível de confiabilidade registrado"]} values={{ Química: "NMC", Capacidade: "72 kWh", Tensão: "400 V", Peso: "480 kg", "Condição conhecida": "Retirada de operação", "SoH, quando disponível": "78%", "Origem do dado de SoH": "Diagnóstico externo", "Nível de confiabilidade registrado": "Alto — documento anexado" }} options={{ Química: ["LFP", "NMC", "NCA", "Outra"], "Condição conhecida": ["Em operação", "Retirada de operação", "Requer avaliação externa"], "Origem do dado de SoH": ["Informado pelo proprietário", "BMS", "Diagnóstico externo", "Documentação técnica"], "Nível de confiabilidade registrado": ["Baixo — autodeclarado", "Médio — BMS ou documentação", "Alto — diagnóstico externo"] }} /><div className="mt-5 flex gap-3 rounded-md border border-primary/25 bg-accent/50 p-4 text-xs text-muted-foreground"><Info className="size-5 shrink-0 text-primary" /><span><strong className="text-foreground">Sobre o SoH:</strong> a origem e a confiabilidade são registradas. A CircularIA não mede fisicamente o SoH; inspeções e ensaios permanecem com agentes habilitados.</span></div></>}
      {step === 2 && <><Fields fields={["Estado", "Cidade/região aproximada"]} values={{ Estado: "SP", "Cidade/região aproximada": "São Paulo (região aproximada)" }} options={{ Estado: ["SP", "MG", "RJ", "PR", "RS", "GO", "PE", "AM"] }} /><p className="mt-4 text-xs text-muted-foreground">O endereço completo e a localização precisa não serão mostrados antes do fechamento protegido da negociação.</p></>}
      {step === 3 && <Options />}
    </div><div className="mt-8"><Disclaimer /></div><div className="mt-7 flex justify-between"><Button variant="outline" disabled={step === 0} onClick={() => setStep((s) => s - 1)}><ChevronLeft />Voltar</Button>{step < 3 ? <Button onClick={() => setStep((s) => s + 1)}>Continuar<ChevronRight /></Button> : <Button onClick={() => navigate({ to: "/matches" })}>Analisar oportunidades<ChevronRight /></Button>}</div></div>
  </AppShell>;
}
function Fields({ fields, options = {}, values = {} }: { fields: string[]; options?: Record<string, string[]>; values?: Record<string, string> }) { return <div className="grid gap-5 md:grid-cols-2">{fields.map((f) => <label key={f}><span className="mb-2 block text-sm font-semibold">{f}</span>{options[f] ? <select defaultValue={values[f]} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{options[f].map((x) => <option key={x}>{x}</option>)}</select> : <Input defaultValue={values[f]} placeholder="Informe o dado disponível" />}</label>)}</div>; }
function Options() { const [selected, setSelected] = useState("Aberto à recomendação da plataforma"); return <div className="grid gap-3">{["Segunda vida", "Remanufatura", "Reciclagem", "Aberto à recomendação da plataforma"].map((x) => <Button key={x} variant="outline" onClick={() => setSelected(x)} className={`h-auto justify-start p-4 text-left ${selected === x ? "border-primary bg-accent" : ""}`}><span className={`size-4 rounded-full border-4 ${selected === x ? "border-primary" : "border-input"}`} />{x}</Button>)}</div>; }
