import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Battery, Check, ChevronLeft, ChevronRight, Info, MapPin, Target } from "lucide-react";
import { useState } from "react";
import { AppShell, Disclaimer } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export const Route=createFileRoute("/cadastrar")({head:()=>({meta:[{title:"Cadastrar ativo — CircularIA"},{name:"description",content:"Cadastre uma bateria ou componente para analisar oportunidades circulares."},{property:"og:title",content:"Cadastrar ativo — CircularIA"},{property:"og:description",content:"Fluxo demonstrativo de cadastro de baterias e componentes."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Register});
const steps=[["Identificação",Battery],["Características técnicas",Battery],["Localização",MapPin],["Objetivo",Target]] as const;
function Register(){const [step,setStep]=useState(0);const navigate=useNavigate();return <AppShell title="Cadastrar ativo" subtitle="Informe os dados disponíveis. Você poderá revisar tudo antes da análise."><div className="mb-7 grid grid-cols-4 overflow-hidden rounded-lg border border-border bg-card">{steps.map(([t,I],i)=>{const Icon=I;return <button key={t} onClick={()=>setStep(i)} className={`flex min-h-20 items-center justify-center gap-2 border-r border-border px-2 text-xs font-semibold last:border-r-0 md:text-sm ${i===step?"bg-primary text-primary-foreground":i<step?"bg-accent text-accent-foreground":"text-muted-foreground"}`}>{i<step?<Check className="size-4"/>:<Icon className="size-4"/>}<span className="hidden sm:inline">{t}</span><span className="sm:hidden">{i+1}</span></button>})}</div><div className="mx-auto max-w-4xl rounded-lg border border-border bg-card p-5 md:p-8"><p className="text-xs font-bold uppercase text-primary">Etapa {step+1} de 4</p><h2 className="mt-2 text-xl font-bold">{steps[step][0]}</h2><div className="mt-7">{step===0&&<Fields fields={["Tipo de ativo","Fabricante","Modelo","Ano","Número de série"]} options={{"Tipo de ativo":["Bateria completa","Módulo","Célula","Outro componente"]}}/>}{step===1&&<><Fields fields={["Química","Capacidade nominal em kWh","Tensão","Peso estimado","SoH, se disponível","Condição geral"]} options={{"Química":["LFP","NMC","NCA","Outra"],"Condição geral":["Em operação","Retirada de operação","Requer avaliação externa"]}}/><div className="mt-5 flex gap-3 rounded-md border border-primary/25 bg-accent/50 p-4 text-xs text-muted-foreground"><Info className="size-5 shrink-0 text-primary"/><span><strong className="text-foreground">Sobre o SoH:</strong> Informação declarada ou proveniente de diagnóstico externo. A plataforma não realiza diagnóstico físico da bateria.</span></div></>}{step===2&&<Fields fields={["CEP","Cidade","Estado","Quantidade disponível"]}/>} {step===3&&<Options/>}</div><div className="mt-8"><Disclaimer/></div><div className="mt-7 flex justify-between"><Button variant="outline" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ChevronLeft/>Voltar</Button>{step<3?<Button onClick={()=>setStep(s=>s+1)}>Continuar<ChevronRight/></Button>:<Button onClick={()=>navigate({to:"/matches"})}>Analisar oportunidades<ChevronRight/></Button>}</div></div></AppShell>}
function Fields({fields,options={}}:{fields:string[];options?:Record<string,string[]>}){return <div className="grid gap-5 md:grid-cols-2">{fields.map((f,i)=><label key={f} className={f==="Número de série"?"md:col-span-2":""}><span className="mb-2 block text-sm font-semibold">{f}</span>{options[f]?<select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option>Selecione</option>{options[f].map(x=><option key={x}>{x}</option>)}</select>:<Input placeholder={i===0?"Digite ou selecione":"Informe o dado disponível"}/>}</label>)}</div>}
function Options(){const [selected,setSelected]=useState("Quero receber recomendação da IA");return <div className="grid gap-3">{["Quero vender","Quero encontrar aplicação de segunda vida","Quero remanufaturar","Quero reciclar","Quero receber recomendação da IA"].map(x=><button key={x} onClick={()=>setSelected(x)} className={`flex items-center gap-3 rounded-md border p-4 text-left text-sm font-semibold ${selected===x?"border-primary bg-accent":"border-border"}`}><span className={`size-4 rounded-full border-4 ${selected===x?"border-primary":"border-input"}`}/>{x}</button>)}</div>}
