import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Building2, Check, FileCheck2, ShieldCheck, Upload, UserRound } from "lucide-react";
import { useState } from "react";
import { Brand, DemoBadge, StatusPill } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/criar-conta")({
  head: () => ({ meta: [
    { title: "Criar conta PF ou PJ — CircularIA" },
    { name: "description", content: "Cadastro demonstrativo de pessoas físicas e jurídicas na CircularIA." },
    { property: "og:title", content: "Criar conta — CircularIA" },
    { property: "og:description", content: "Cadastre uma pessoa física ou empresa para participar da rede CircularIA." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: RegisterAccount,
});

type Kind = "PF" | "PJ";
const pfUses = ["Vender/destinar bateria", "Comprar bateria", "Interesse em segunda vida", "Outro"];
const pjProfiles = ["Ofertante", "Comprador", "Reciclador", "Remanufaturador", "Consumidor de segunda vida", "Operador logístico", "Diagnóstico", "Integrador", "Outro"];

function RegisterAccount() {
  const [kind, setKind] = useState<Kind>("PF");
  const [step, setStep] = useState(1);
  const [technical, setTechnical] = useState(false);
  const finished = step === 4;
  return <main className="min-h-screen bg-muted"><header className="border-b border-border bg-background"><div className="mx-auto flex min-h-16 max-w-6xl items-center justify-between px-5"><Brand/><DemoBadge/></div></header><div className="mx-auto max-w-6xl px-5 py-8"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Voltar</Link>
    <div className="mt-5 grid gap-6 lg:grid-cols-[1fr_300px]"><section className="rounded-lg border border-border bg-card p-6 md:p-8">{!finished ? <><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-primary">Etapa {step} de 3</p><h1 className="mt-2 text-2xl font-bold">{step === 1 ? "Tipo de conta" : step === 2 ? kind === "PF" ? "Dados da Pessoa Física" : "Dados da Pessoa Jurídica" : "Verificação e segurança"}</h1></div><StatusPill tone="warn">Cadastro demonstrativo</StatusPill></div>
      {step === 1 && <div className="mt-7 grid gap-4 sm:grid-cols-2"><Choice active={kind === "PF"} icon={UserRound} title="Pessoa Física" text="Para uso individual, compra ou destinação de baterias." onClick={() => setKind("PF")}/><Choice active={kind === "PJ"} icon={Building2} title="Pessoa Jurídica" text="Para empresas e agentes da cadeia de circularidade." onClick={() => setKind("PJ")}/></div>}
      {step === 2 && (kind === "PF" ? <PFFields/> : <PJFields technical={technical} setTechnical={setTechnical}/>)}
      {step === 3 && <VerificationFields kind={kind} technical={technical}/>}<div className="mt-8 flex justify-between"><Button variant="outline" disabled={step === 1} onClick={() => setStep((value) => Math.max(1, value - 1))}>Voltar</Button><Button onClick={() => setStep((value) => Math.min(4, value + 1))}>{step === 3 ? "Enviar cadastro" : "Continuar"}<ArrowRight/></Button></div></> : <Completion kind={kind} technical={technical}/>}</section>
      <aside className="space-y-4"><div className="rounded-lg border border-primary/30 bg-accent p-5"><ShieldCheck className="size-7 text-primary"/><h2 className="mt-4 font-bold">Verificação aplicável</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">A CircularIA realiza verificações de identidade, documentação empresarial e habilitação técnica aplicável para aumentar segurança, rastreabilidade e confiabilidade.</p></div><div className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold">Status possíveis</h2><div className="mt-3 flex flex-wrap gap-2">{(kind === "PF" ? ["Em análise", "Verificado", "Pendente", "Rejeitado"] : ["Enviado", "Em análise", "Validado", "Pendente"]).map((status) => <StatusPill key={status}>{status}</StatusPill>)}</div></div></aside>
    </div></div></main>;
}

function PFFields() { return <div className="mt-7"><Grid fields={["Nome completo", "CPF", "Data de nascimento", "E-mail", "Telefone", "Estado", "Cidade"]}/><ChoiceGroup title="Perfil de uso" items={pfUses}/><label className="mt-6 block"><span className="mb-2 block text-sm font-semibold">Registro profissional (opcional, quando aplicável)</span><Input placeholder="Conselho, número e estado"/></label></div>; }
function PJFields({ technical, setTechnical }: { technical: boolean; setTechnical: (value: boolean) => void }) { return <div className="mt-7 space-y-7"><div><h2 className="mb-4 font-bold">Empresa</h2><Grid fields={["Razão social", "Nome fantasia", "CNPJ", "Segmento", "Porte", "Estado", "Cidade"]}/><ChoiceGroup title="Perfil de atuação" items={pjProfiles}/></div><div><h2 className="mb-4 font-bold">Responsável legal</h2><Grid fields={["Nome", "Cargo", "CPF", "E-mail", "Telefone"]}/></div><div className="rounded-md border border-border p-4"><p className="font-semibold">A atividade exige responsável técnico?</p><div className="mt-3 flex gap-2"><Button type="button" variant={technical ? "default" : "outline"} onClick={() => setTechnical(true)}>Sim</Button><Button type="button" variant={!technical ? "default" : "outline"} onClick={() => setTechnical(false)}>Não</Button></div>{technical && <div className="mt-5"><Grid fields={["Nome do responsável técnico", "Profissão", "Conselho: CREA / CRT / outro", "Nº do registro", "Estado", "Certificações"]}/></div>}<p className="mt-3 text-xs text-muted-foreground">CREA ou CRT é solicitado somente quando aplicável à atividade; não representa garantia absoluta de qualidade.</p></div></div>; }
function VerificationFields({ kind, technical }: { kind: Kind; technical: boolean }) { const docs = kind === "PF" ? ["Documento de identificação", "Comprovante de CPF"] : ["Cartão CNPJ", "Documentação empresarial", "Documento do responsável legal", ...(technical ? ["Comprovante do registro técnico"] : [])]; return <div className="mt-7"><div className="grid gap-4 sm:grid-cols-2">{docs.map((doc) => <div key={doc} className="rounded-md border border-dashed border-input p-5 text-center"><Upload className="mx-auto size-5 text-primary"/><p className="mt-2 text-sm font-semibold">{doc}</p><Button type="button" size="sm" variant="outline" className="mt-3">Selecionar arquivo</Button><p className="mt-2 text-xs text-muted-foreground">Upload demonstrativo e privado</p></div>)}</div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Senha de acesso</span><Input type="password" defaultValue="demonstracao"/></label><label><span className="mb-2 block text-sm font-semibold">Senha de transação</span><Input type="password" inputMode="numeric" defaultValue="1234"/></label></div><div className="mt-6 space-y-3">{["Confirmo a verificação do e-mail e telefone", "Aceito os termos de uso", "Aceito a política de tratamento de dados"].map((item) => <label key={item} className="flex items-center gap-3 text-sm"><input type="checkbox" defaultChecked className="size-4 accent-primary"/>{item}</label>)}</div></div>; }
function Completion({ kind, technical }: { kind: Kind; technical: boolean }) { return <div className="py-10 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-accent text-primary"><FileCheck2 className="size-8"/></span><StatusPill tone="warn">{kind === "PF" ? "Em análise" : "Enviado"}</StatusPill><h1 className="mt-5 text-2xl font-bold">Cadastro enviado para verificação</h1><p className="mx-auto mt-3 max-w-lg text-sm text-muted-foreground">Nesta demonstração, a análise pode ser concluída imediatamente para mostrar os selos aplicáveis.</p><div className="mx-auto mt-6 grid max-w-md gap-2 text-left"><span className="flex items-center gap-2 rounded-md bg-accent p-3 text-sm font-bold"><Check className="size-4 text-primary"/>{kind === "PF" ? "Pessoa Física Verificada" : "Empresa Verificada"}</span>{kind === "PJ" && technical && <span className="flex items-center gap-2 rounded-md bg-accent p-3 text-sm font-bold"><Check className="size-4 text-primary"/>Responsável Técnico Verificado</span>}</div><Button className="mt-7" asChild><Link to="/entrar">Ir para o login<ArrowRight/></Link></Button></div>; }
function Grid({ fields }: { fields: string[] }) { return <div className="grid gap-4 sm:grid-cols-2">{fields.map((field) => <label key={field}><span className="mb-2 block text-sm font-semibold">{field}</span><Input placeholder={`Informe ${field.toLowerCase()}`}/></label>)}</div>; }
function ChoiceGroup({ title, items }: { title: string; items: string[] }) { return <fieldset className="mt-6"><legend className="mb-3 text-sm font-semibold">{title}</legend><div className="flex flex-wrap gap-2">{items.map((item) => <label key={item} className="flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm"><input type="checkbox" className="accent-primary"/>{item}</label>)}</div></fieldset>; }
function Choice({ active, icon: Icon, title, text, onClick }: { active: boolean; icon: typeof UserRound; title: string; text: string; onClick: () => void }) { return <Button type="button" variant="outline" onClick={onClick} className={`h-auto items-start justify-start p-5 text-left ${active ? "border-primary bg-accent" : ""}`}><Icon className="mt-0.5 size-6 shrink-0 text-primary"/><span><strong className="block text-base">{title}</strong><small className="mt-1 block whitespace-normal font-normal text-muted-foreground">{text}</small></span></Button>; }