import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BatteryCharging, BrainCircuit, FileText, Lock, MessageSquare, Network, PackageCheck } from "lucide-react";
import { AppShell, DemoBadge, LockedFeature, Pillars, SectionTitle, StatCard } from "@/components/circular-ui";
import { ChemistryChart, DestinationChart } from "@/components/charts-demo";
import { Button } from "@/components/ui/button";
import { useCircular } from "@/lib/circular-store";
export const Route = createFileRoute("/dashboard")({ head: () => ({ meta: [{ title: "Visão Geral — CircularIA" }, { name: "description", content: "Painel adaptável aos serviços CircularIA contratados." }, { property: "og:title", content: "Visão Geral — CircularIA" }, { property: "og:description", content: "Ativos, negociações e inteligência em uma visão integrada." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Dashboard });
function Dashboard() { const { profile, conversations } = useCircular(); const active = conversations.filter((c) => c.status !== "Operação concluída").length; const proposals = conversations.filter((c) => c.proposals.length > 0).length; return <AppShell title="Visão Geral" subtitle={`Experiência adaptada para ${profile.role} e os serviços contratados.`} actions={<Button size="sm" asChild><Link to="/cadastrar">Cadastrar ativo</Link></Button>}><div className="mb-6"><Pillars /></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Minhas baterias" value="4" detail="Dados demonstrativos" icon={BatteryCharging} /><StatCard label="Matches" value="16" detail="Dados demonstrativos" icon={Network} /><StatCard label="Conversas ativas" value={String(active)} detail="Dados demonstrativos" icon={MessageSquare} /><StatCard label="Propostas" value={String(proposals)} detail="Dados demonstrativos" icon={FileText} /><StatCard label="Negociações" value="3" detail="Dados demonstrativos" icon={PackageCheck} /></div>
  {profile.plans.intelligence ? <><div className="mt-7 flex items-center justify-between"><SectionTitle aside={<DemoBadge />}>CircularIA Intelligence</SectionTitle><Button variant="outline" size="sm" asChild><Link to="/inteligencia">Abrir painel</Link></Button></div><div className="grid gap-5 lg:grid-cols-2"><DestinationChart /><ChemistryChart /></div></> : <div className="mt-7"><LockedFeature product="CircularIA Intelligence" description="Assine para acessar dados de mercado, oferta, demanda, regiões, químicas, tendências e análises da cadeia de baterias." /></div>}
  <div className="mt-7 rounded-lg border border-primary/25 bg-accent/60 p-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><DemoBadge /><h2 className="mt-3 text-xl font-bold">Demonstre o fluxo completo de circularidade.</h2><p className="mt-2 text-sm text-muted-foreground">Cadastro → matching → identidade protegida → conversa moderada → proposta → acordo → taxa → Journey e Intelligence.</p></div><Button asChild><Link to="/cadastrar">Iniciar demonstração <ArrowRight /></Link></Button></div></div>
  <div className="mt-8"><SectionTitle>Atividade recente</SectionTitle><div className="divide-y divide-border rounded-lg border border-border bg-card">{[["Match de 91% identificado", "Pack NMC 72 kWh · empresa anonimizada", "Agora"], ["Contraproposta recebida", "BAT-00192 · Empresa Verificada #5281", "12 min"], ["Dados anonimizados agregados", "Indicadores de oferta × demanda", "1 h"]].map((x) => <div key={x[0]} className="flex items-center gap-4 p-4"><span className="rounded-md bg-accent p-2 text-primary"><BrainCircuit className="size-4" /></span><div className="flex-1"><p className="text-sm font-semibold">{x[0]}</p><p className="text-xs text-muted-foreground">{x[1]} · Dados demonstrativos</p></div><span className="text-xs text-muted-foreground">{x[2]}</span></div>)}</div></div>
  {!profile.plans.journey && <div className="mt-6 rounded-lg border border-border bg-card p-4 text-sm text-muted-foreground"><Lock className="mr-2 inline size-4" />Journey não contratado. O Marketplace e o Intelligence funcionam de forma independente.</div>}
  </AppShell>; }
