import { createFileRoute, Link } from "@tanstack/react-router";
import { BatteryCharging, Building2, MapPin, MessageSquare, Search, ShieldCheck } from "lucide-react";
import { AppShell, DemoBadge, StatCard, VerifiedBadge } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";
import { useCircular } from "@/lib/circular-store";
import { demandProfile } from "@/lib/demo-data";
export const Route = createFileRoute("/empresa")({ head: () => ({ meta: [{ title: "Perfil da Empresa — CircularIA" }, { name: "description", content: "Perfil empresarial, demanda e oportunidades." }, { property: "og:title", content: "Perfil da Empresa — CircularIA" }, { property: "og:description", content: "Gestão demonstrativa da empresa participante." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Company });
function Company() { const { profile, conversations } = useCircular(); return <AppShell title="Perfil da Empresa" subtitle="Gerencie o perfil, a demanda e os serviços contratados pela empresa."><div className="rounded-lg border border-border bg-card p-6"><div className="flex flex-col gap-6 md:flex-row md:items-center"><span className="grid size-20 place-items-center rounded-lg bg-foreground text-primary"><Building2 className="size-9" /></span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-bold">{profile.company}</h2><VerifiedBadge status={profile.verification} /><DemoBadge /></div><p className="mt-2 text-sm text-muted-foreground">{profile.role} · <MapPin className="inline size-3" /> {profile.region}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline">Editar perfil</Button><Button asChild><Link to="/empresa/demanda"><Search />Perfil de demanda</Link></Button></div></div><div className="mt-7 grid gap-4 border-t border-border pt-6 md:grid-cols-3"><Info label="Interesses" value={demandProfile.chemistry} /><Info label="Faixa desejada" value={demandProfile.capacity} /><Info label="Capacidade mensal" value={demandProfile.absorption} /></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><StatCard label="Oportunidades compatíveis" value="18" detail="Dados demonstrativos" /><StatCard label="Conversas ativas" value={String(conversations.filter((c) => c.status !== "Operação concluída").length)} detail="Dados demonstrativos" /><StatCard label="Serviços contratados" value={String(1 + Number(profile.plans.intelligence) + Number(profile.plans.journey))} detail="Marketplace + adicionais" /></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold">Oportunidades compatíveis</h2><div className="mt-4 space-y-3">{["Pack NMC 72 kWh · 91%", "Pack LFP 52 kWh · 88%", "Módulos NMC 5 kWh · 84%"].map((x) => <div key={x} className="flex items-center justify-between rounded-md bg-muted p-3 text-sm font-semibold"><span className="flex items-center gap-2"><BatteryCharging className="size-4 text-primary" />{x}</span><Button size="sm" variant="ghost" asChild><Link to="/matches">Abrir</Link></Button></div>)}</div></div><div className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold">Acesso rápido</h2><div className="mt-4 grid gap-3"><Button variant="outline" className="justify-start" asChild><Link to="/empresa/conversas"><MessageSquare />Minhas Conversas</Link></Button><Button variant="outline" className="justify-start" asChild><Link to="/empresa/documentacao"><ShieldCheck />Documentação e Verificação</Link></Button><Button variant="outline" className="justify-start" asChild><Link to="/empresa/plano">Plano e Serviços</Link></Button></div></div></div></AppShell>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-semibold">{value}</p></div>; }
