import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BatteryCharging, Boxes, BrainCircuit, Factory, LogIn, Recycle, RotateCcw, Search, ShieldCheck, UserPlus, Zap } from "lucide-react";
import { Brand, Pillars } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({ head:()=>({meta:[{title:"CircularIA — Circularidade de baterias e componentes"},{name:"description",content:"Plataforma inteligente de circularidade para baterias e componentes de veículos eletrificados."},{property:"og:title",content:"CircularIA — Circularidade inteligente"},{property:"og:description",content:"Conecte baterias e componentes da eletrificação a novos ciclos de uso, valor e recuperação."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: Home });

function Home(){return <div className="min-h-screen bg-background">
<header className="border-b border-border bg-background"><div className="mx-auto flex min-h-18 max-w-7xl flex-wrap items-center justify-between gap-3 px-5 py-3"><Brand/><nav className="hidden gap-7 text-sm font-medium lg:flex"><a href="#como-funciona">Como funciona</a><a href="#perfis">Para empresas</a><a href="#valor">Circularidade</a></nav><div className="flex gap-2"><Button variant="ghost" asChild><Link to="/entrar"><LogIn/>Entrar</Link></Button><Button asChild><Link to="/criar-conta"><UserPlus/>Criar conta</Link></Button></div></div></header>
<main><section className="grid-texture overflow-hidden bg-foreground text-primary-foreground"><div className="mx-auto grid min-h-[660px] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.15fr_.85fr]"><div className="animate-rise"><div className="mb-6 inline-flex items-center gap-2 rounded-md border border-primary/40 bg-primary/10 px-3 py-2 text-xs font-bold uppercase text-primary"><Zap className="size-4"/> Ecossistema inteligente de circularidade</div><h1 className="max-w-4xl text-4xl font-bold leading-[1.08] md:text-6xl">Conectando ativos da eletrificação ao próximo ciclo de valor.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-primary-foreground/70">Conectamos baterias, componentes eletrônicos e sistemas da eletrificação a novos ciclos de uso, valor e recuperação, com IA explicável para recomendar destinos e gerar inteligência de mercado.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/cadastrar">Cadastrar ativo <ArrowRight/></Link></Button><Button size="lg" variant="outline" className="border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground/10" asChild><Link to="/marketplace">Encontrar oportunidades <Search/></Link></Button></div><p className="mt-5 flex items-center gap-2 text-xs text-primary-foreground/55"><ShieldCheck className="size-4"/>IA explicável como apoio à decisão. Não substitui avaliação técnica.</p></div>
<div className="relative hidden min-h-[460px] lg:block"><div className="absolute inset-4 rounded-lg border border-primary/30 bg-primary-foreground/5 p-7"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase text-primary">Rede CircularIA</span><span className="size-2 rounded-full bg-primary"/></div><div className="relative mt-8 h-[350px]"><div className="absolute left-[42%] top-[38%] grid size-28 place-items-center rounded-full border border-primary/60 bg-foreground shadow-2xl"><BrainCircuit className="size-10 text-primary"/><span className="text-xs font-bold">IA explicável</span></div>{[["Ativos",Boxes,"left-0 top-3"],["Reutilização",Zap,"right-0 top-4"],["Remanufatura",RotateCcw,"left-4 bottom-3"],["Reciclagem",Recycle,"right-4 bottom-2"]].map(([t,I,p])=>{const Icon=I as typeof Zap;return <div key={t as string} className={`absolute ${p} w-36 rounded-md border border-primary-foreground/15 bg-primary-foreground/10 p-4`}><Icon className="mb-3 text-primary"/><p className="text-sm font-bold">{t as string}</p></div>})}<svg className="absolute inset-0 -z-10 h-full w-full" aria-hidden><path d="M110 60 L250 160 L410 60 M110 300 L250 200 L410 300" fill="none" stroke="currentColor" className="text-primary/40" strokeDasharray="5 5"/></svg></div></div></div></div></section>
<section id="como-funciona" className="border-b border-border py-20"><div className="mx-auto max-w-7xl px-5"><p className="text-xs font-bold uppercase text-primary">Da origem ao melhor destino</p><h2 className="mt-3 text-3xl font-bold">Um processo conectado, transparente e explicável</h2><div className="mt-10 grid gap-2 lg:grid-cols-6">{["Ativo disponível","Cadastro técnico","IA analisa oportunidades","Matching","Comparar destinos","Novo ciclo de valor"].map((x,i)=><div key={x} className="relative border-t-2 border-primary bg-card p-4"><span className="text-xs font-bold text-primary">0{i+1}</span><p className="mt-5 text-sm font-bold">{x}</p>{i<5&&<ArrowRight className="absolute -right-4 top-1/2 z-10 hidden size-5 text-primary lg:block"/>}</div>)}</div></div></section>
<section id="perfis" className="bg-muted py-20"><div className="mx-auto max-w-7xl px-5"><div className="grid gap-8 lg:grid-cols-2"><Profile icon={Boxes} title="Quem possui ou oferta ativos" types="Montadoras · Frotistas · Concessionárias · Oficinas · Integradores · Empresas" steps="Cadastrar ativo → Receber matches → Comparar destinos → Negociar" action="Cadastrar ativo" to="/cadastrar"/><Profile icon={Factory} title="Quem busca ativos da eletrificação" types="Recicladores · Remanufaturadores · Empresas de segunda vida · Reparadores" steps="Cadastrar interesse → Encontrar ativos → Receber alertas → Realizar match" action="Explorar ativos" to="/marketplace"/></div></div></section>
<section id="valor" className="py-20"><div className="mx-auto max-w-7xl px-5"><p className="text-xs font-bold uppercase text-primary">Do fim de uso ao novo valor</p><h2 className="mt-3 max-w-2xl text-3xl font-bold">O fim de uma aplicação pode ser o início de outro ciclo de valor.</h2><p className="mt-4 max-w-3xl text-muted-foreground">Baterias, componentes eletrônicos e sistemas retirados de sua aplicação original ainda podem preservar valor funcional, econômico, energético ou material.</p><div className="mt-10 grid gap-4 md:grid-cols-3">{[["Reutilizar","Prolongar o uso de ativos tecnicamente adequados em novas aplicações.",Zap],["Reparar e remanufaturar","Recuperar componentes, sistemas e funcionalidade para um novo uso.",RotateCcw],["Reciclar","Recuperar materiais críticos quando não houver alternativa de maior valor.",Recycle]].map(([t,d,I])=>{const Icon=I as typeof Zap;return <div key={t as string} className="rounded-lg border border-border bg-card p-6"><Icon className="size-7 text-primary"/><h3 className="mt-8 text-xl font-bold">{t as string}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{d as string}</p></div>})}</div><div className="mt-14"><Pillars/></div></div></section></main>
<footer className="border-t border-border py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 px-5 text-xs text-muted-foreground md:flex-row"><Brand/><p>Protótipo conceitual · Hackathon Jump Start 2026 · Dados demonstrativos</p></div></footer></div>}
function Profile({icon:Icon,title,types,steps,action,to}:{icon:typeof BatteryCharging;title:string;types:string;steps:string;action:string;to:"/cadastrar"|"/marketplace"}){return <div className="rounded-lg border border-border bg-card p-7"><span className="grid size-12 place-items-center rounded-md bg-accent text-primary"><Icon/></span><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-3 text-sm text-muted-foreground">{types}</p><div className="mt-6 border-l-2 border-primary pl-4 text-sm font-semibold">{steps}</div><Button className="mt-7" asChild><Link to={to}>{action}<ArrowRight/></Link></Button></div>}
