import { ClientOnly, createFileRoute } from "@tanstack/react-router";
import { lazy, Suspense, useMemo, useState } from "react";
import { Activity, Filter, Layers3, Lock, MapPin } from "lucide-react";
import { AppShell, DemoBadge, LockedFeature } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";
import { useCircular } from "@/lib/circular-store";
import { counterparts } from "@/lib/demo-data";
const MapClient = lazy(() => import("@/components/map/circular-map.client"));
export const Route = createFileRoute("/mapa")({ head: () => ({ meta: [{ title: "Mapa da Circularidade — CircularIA" }, { name: "description", content: "Mapa real interativo do ecossistema brasileiro de baterias." }, { property: "og:title", content: "Mapa da Circularidade — CircularIA" }, { property: "og:description", content: "Ativos, agentes e camadas agregadas demonstrativas." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CircularMap });
const types = ["Todos", "Ativos disponíveis", "Consumidor de segunda vida", "Remanufaturador", "Reciclador", "Operador logístico", "Parceiro de diagnóstico"];
const regions = ["Todas", "Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul"];
function CircularMap() { const { plans } = useCircular(); const [type, setType] = useState("Todos"); const [region, setRegion] = useState("Todas"); const [chem, setChem] = useState("Todas"); const [selected, setSelected] = useState("#1842"); const [layer, setLayer] = useState("Operacional"); const filtered = useMemo(() => counterparts.filter((p) => (type === "Todos" || p.type === type) && (region === "Todas" || p.region === region) && (chem === "Todas" || p.chemistries.includes(chem) || p.chemistries.includes("Todas"))), [type, region, chem]); const active = counterparts.find((p) => p.code === selected) ?? filtered[0]; return <AppShell title="Mapa da Circularidade" subtitle="Explore o território brasileiro com localização aproximada, filtros, zoom, pontos agrupados visualmente e camadas por serviço.">
  <div className="mb-4 flex flex-wrap items-end gap-3 rounded-lg border border-border bg-card p-4"><Select label="Tipo de agente" value={type} set={setType} options={types} /><Select label="Química" value={chem} set={setChem} options={["Todas", "NMC", "LFP", "NCA"]} /><Select label="Região" value={region} set={setRegion} options={regions} /><Select label="Estado" value="Todos" set={() => {}} options={["Todos", "SP", "MG", "RJ", "PR", "RS", "GO", "PE", "AM"]} /><Select label="Destino" value="Todos" set={() => {}} options={["Todos", "Segunda vida", "Remanufatura", "Reciclagem"]} /><Select label="Disponibilidade" value="Ativos" set={() => {}} options={["Ativos", "Todas"]} /><Button variant="outline"><Filter />{filtered.length} pontos</Button></div>
  <div className="grid gap-5 xl:grid-cols-[1fr_350px]"><div className="relative overflow-hidden rounded-lg border border-border bg-card"><ClientOnly fallback={<div className="grid h-[640px] place-items-center text-sm text-muted-foreground">Carregando mapa do Brasil…</div>}>{<Suspense fallback={<div className="grid h-[640px] place-items-center text-sm text-muted-foreground">Carregando mapa do Brasil…</div>}><MapClient points={filtered} selected={selected} onSelect={setSelected} onRegion={setRegion} /></Suspense>}</ClientOnly><div className="pointer-events-none absolute bottom-6 left-4 z-[500]"><DemoBadge /></div></div>
    <aside className="space-y-4"><div className="rounded-lg border border-border bg-card p-5"><p className="text-xs font-bold uppercase text-primary">Região selecionada</p><h2 className="mt-2 text-xl font-bold">{region === "Todas" ? active?.region ?? "Brasil" : region}</h2><p className="mt-2 text-sm text-muted-foreground">{filtered.length} agentes ou ativos visíveis · localização aproximada</p>{active && <div className="mt-4 rounded-md bg-muted p-4"><p className="font-bold">Empresa Verificada {active.code}</p><p className="mt-1 text-sm">Tipo: {active.type}</p><p className="mt-1 text-sm">Região: {active.region}</p><p className="mt-1 text-sm">Químicas aceitas: {active.chemistries.join(", ")}</p><p className="mt-1 text-sm">Demandas ativas: {active.demands}</p></div>}</div>
    <div className="rounded-lg border border-border bg-card p-5"><h2 className="flex items-center gap-2 font-bold"><Layers3 className="size-4 text-primary" />Camadas de informação</h2><div className="mt-3 grid gap-2">{["Operacional", "Heatmap de oferta", "Heatmap de demanda", "Concentração por química", "Gargalos logísticos", "Tendências temporais"].map((x, i) => <Button key={x} variant={layer === x ? "default" : "outline"} disabled={i > 0 && !plans.intelligence} onClick={() => setLayer(x)} className="justify-start">{i > 0 && !plans.intelligence ? <Lock /> : <Activity />}{x}</Button>)}</div>{!plans.intelligence && <p className="mt-3 text-xs text-muted-foreground">Camadas avançadas requerem CircularIA Intelligence.</p>}</div>
    <div className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold">Legenda</h2><div className="mt-3 grid gap-2 text-xs">{[["bg-primary", "Ativos disponíveis"], ["bg-data-b", "Segunda vida"], ["bg-data-c", "Remanufatura"], ["bg-destructive", "Reciclagem"], ["bg-data-d", "Logística"], ["bg-muted-foreground", "Diagnóstico"]].map(([c, l]) => <p key={l} className="flex items-center gap-2"><span className={`size-3 rounded-full ${c}`} />{l}</p>)}</div></div></aside></div>
  {plans.intelligence && layer !== "Operacional" && <div className="mt-5 rounded-lg border border-primary/30 bg-accent/40 p-5"><h2 className="font-bold">Camada ativa: {layer}</h2><p className="mt-2 text-sm text-muted-foreground">Visualização demonstrativa agregada e anonimizada. O Sudeste concentra maior oferta, enquanto o Centro-Oeste apresenta possível baixa capacidade de absorção.</p><div className="mt-3"><DemoBadge /></div></div>}
  {!plans.intelligence && <div className="mt-5"><LockedFeature product="CircularIA Intelligence" description="Assine para acessar heatmaps de oferta e demanda, concentração por química, gargalos logísticos e tendências temporais." /></div>}
  </AppShell>; }
function Select({ label, value, set, options }: { label: string; value: string; set: (v: string) => void; options: string[] }) { return <label><span className="mb-1 block text-[10px] font-bold uppercase text-muted-foreground">{label}</span><select value={value} onChange={(e) => set(e.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-xs">{options.map((o) => <option key={o}>{o}</option>)}</select></label>; }
