import { ClientOnly, createFileRoute, Link } from "@tanstack/react-router";
import { lazy, Suspense, useMemo, useState } from "react";
import { Activity, Filter, Layers3 } from "lucide-react";
import { AppShell, DemoBadge, LockedFeature } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";
import { useCircular } from "@/lib/circular-store";
import { counterparts } from "@/lib/demo-data";
import type { MapMode } from "@/components/map/circular-map.client";
const MapClient = lazy(() => import("@/components/map/circular-map.client"));
export const Route = createFileRoute("/mapa")({ head: () => ({ meta: [{ title: "Mapa da Circularidade — CircularIA" }, { name: "description", content: "Mapa real interativo do ecossistema brasileiro de baterias." }, { property: "og:title", content: "Mapa da Circularidade — CircularIA" }, { property: "og:description", content: "Ativos, agentes e camadas agregadas demonstrativas." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CircularMap });
const types = ["Todos", "Ativos disponíveis", "Consumidor de segunda vida", "Remanufaturador", "Reciclador", "Operador logístico", "Parceiro de diagnóstico"];
const regions = ["Todas", "Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul"];
const modes: MapMode[] = ["Pontos", "Heatmap de Oferta", "Heatmap de Demanda", "Heatmap de Segunda Vida", "Heatmap de Remanufatura", "Heatmap de Reciclagem"];
const summaries: Record<string, { assets: string; destinations: string; demands: string; capacity: string; second: string; reman: string; recycle: string; chemistry: string }> = {
  Brasil: { assets: "1.248", destinations: "186", demands: "324", capacity: "38,4 MWh", second: "42%", reman: "31%", recycle: "27%", chemistry: "NMC" },
  Sudeste: { assets: "674", destinations: "92", demands: "168", capacity: "21,7 MWh", second: "46%", reman: "33%", recycle: "21%", chemistry: "NMC" },
  SP: { assets: "386", destinations: "54", demands: "101", capacity: "12,8 MWh", second: "49%", reman: "32%", recycle: "19%", chemistry: "NMC" },
  Sul: { assets: "262", destinations: "41", demands: "73", capacity: "8,2 MWh", second: "37%", reman: "38%", recycle: "25%", chemistry: "LFP" },
};
function CircularMap() { const { plans } = useCircular(); if (!plans.intelligence) return <AppShell title="Mapa da Circularidade" subtitle="Inteligência geográfica agregada da rede CircularIA."><LockedFeature product="CircularIA Intelligence" description="O Mapa da Circularidade transforma os dados da rede CircularIA em inteligência geográfica sobre oferta, demanda e destinos."><Button variant="outline" asChild><Link to="/empresa/plano">Conhecer CircularIA Intelligence</Link></Button></LockedFeature></AppShell>; return <IntelligenceMap/>; }
function IntelligenceMap() { const [type, setType] = useState("Todos"); const [region, setRegion] = useState("Todas"); const [state, setState] = useState("Todos"); const [chem, setChem] = useState("Todas"); const [assetType, setAssetType] = useState("Todos"); const [destination, setDestination] = useState("Todos"); const [availability, setAvailability] = useState("Todos"); const [selected, setSelected] = useState("#1842"); const [mode, setMode] = useState<MapMode>("Pontos"); const filtered = useMemo(() => counterparts.filter((p) => (type === "Todos" || p.type === type) && (region === "Todas" || p.region === region) && (state === "Todos" || p.state === state) && (chem === "Todas" || p.chemistries.includes(chem) || p.chemistries.includes("Todas")) && (assetType === "Todos" || (assetType === "Bateria completa" ? p.type === "Ativos disponíveis" : true)) && (destination === "Todos" || p.type.includes(destination) || (destination === "Segunda vida" && p.type === "Consumidor de segunda vida")) && (availability === "Todos" || p.demands > 0)), [type, region, state, chem, assetType, destination, availability]); const active = counterparts.find((p) => p.code === selected) ?? filtered[0]; const summaryKey = state !== "Todos" ? state : region !== "Todas" ? region : "Brasil"; const summary = summaries[summaryKey] ?? summaries["Brasil"]; if (!summary) return null; return <AppShell title="Mapa da Circularidade" subtitle="Recurso CircularIA Intelligence com dados agregados, anonimizados e localização aproximada.">
  <div className="mb-4 flex flex-wrap items-end gap-3 rounded-lg border border-border bg-card p-4"><Select label="Estado" value={state} set={(value) => { setState(value); if (value === "SP" || value === "MG" || value === "RJ") setRegion("Sudeste"); else if (value === "PR" || value === "RS") setRegion("Sul"); }} options={["Todos", "SP", "MG", "RJ", "PR", "RS", "GO", "PE", "AM"]} /><Select label="Região" value={region} set={(value) => { setRegion(value); setState("Todos"); }} options={regions} /><Select label="Química" value={chem} set={setChem} options={["Todas", "NMC", "LFP", "NCA"]} /><Select label="Tipo de ativo" value={assetType} set={setAssetType} options={["Todos", "Bateria completa", "Módulo", "Componente"]} /><Select label="Tipo de agente" value={type} set={setType} options={types} /><Select label="Destinação" value={destination} set={setDestination} options={["Todos", "Segunda vida", "Remanufatura", "Reciclagem"]} /><Select label="Disponibilidade" value={availability} set={setAvailability} options={["Todos", "Disponíveis agora"]} /><Button variant="outline"><Filter />{filtered.length} resultados</Button></div>
  <div className="mb-4 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Modos do mapa">{modes.map((item) => <Button key={item} role="tab" aria-selected={mode === item} variant={mode === item ? "default" : "outline"} onClick={() => setMode(item)} className="shrink-0">{item === "Pontos" ? <Activity/> : <Layers3/>}{item}</Button>)}</div>
  <div className="grid gap-5 xl:grid-cols-[1fr_350px]"><div className="relative overflow-hidden rounded-lg border border-border bg-card"><ClientOnly fallback={<div className="grid h-[640px] place-items-center text-sm text-muted-foreground">Carregando mapa do Brasil…</div>}>{<Suspense fallback={<div className="grid h-[640px] place-items-center text-sm text-muted-foreground">Carregando mapa do Brasil…</div>}><MapClient points={filtered} selected={selected} onSelect={setSelected} onRegion={setRegion} onState={setState} mode={mode} state={state} region={region} /></Suspense>}</ClientOnly><div className="pointer-events-none absolute bottom-6 left-4 z-[500]"><DemoBadge /></div></div>
    <aside className="space-y-4"><div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-bold uppercase text-primary">{summaryKey === "SP" ? "São Paulo" : summaryKey}</p><h2 className="mt-2 text-xl font-bold">Resumo geográfico</h2></div><DemoBadge/></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm">{[["Ativos disponíveis", summary.assets], ["Destinos", summary.destinations], ["Demandas", summary.demands], ["Capacidade cadastrada", summary.capacity], ["Segunda vida", summary.second], ["Remanufatura", summary.reman], ["Reciclagem", summary.recycle], ["Química predominante", summary.chemistry]].map(([label, value]) => <div key={label} className="rounded-md bg-muted p-3"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-bold">{value}</dd></div>)}</dl></div>
    {mode === "Pontos" && active && <div className="rounded-lg border border-border bg-card p-5"><p className="font-bold">Empresa Verificada {active.code}</p><p className="mt-1 text-sm">Tipo: {active.type}</p><p className="mt-1 text-sm">Região: {active.region}</p><p className="mt-1 text-sm">Químicas: {active.chemistries.join(" / ")}</p><p className="mt-3 text-xs text-muted-foreground">Localização aproximada. Identidade preservada.</p></div>}
    <div className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold">Legenda</h2><div className="mt-3 grid gap-2 text-xs">{[["bg-primary", "Ativos disponíveis"], ["bg-data-b", "Segunda vida"], ["bg-data-c", "Remanufatura"], ["bg-destructive", "Reciclagem"], ["bg-data-d", "Logística"], ["bg-muted-foreground", "Diagnóstico"]].map(([c, l]) => <p key={l} className="flex items-center gap-2"><span className={`size-3 rounded-full ${c}`} />{l}</p>)}</div></div></aside></div>
  {mode !== "Pontos" && <div className="mt-5 rounded-lg border border-primary/30 bg-accent/40 p-5"><h2 className="font-bold">Camada ativa: {mode}</h2><p className="mt-2 text-sm text-muted-foreground">Visualização por círculos de intensidade com dados agregados e anonimizados. Alta concentração de baterias NMC no Sudeste.</p><div className="mt-3"><DemoBadge /></div></div>}
  </AppShell>; }
function Select({ label, value, set, options }: { label: string; value: string; set: (v: string) => void; options: string[] }) { return <label><span className="mb-1 block text-[10px] font-bold uppercase text-muted-foreground">{label}</span><select value={value} onChange={(e) => set(e.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-xs">{options.map((o) => <option key={o}>{o}</option>)}</select></label>; }
