import { createFileRoute, Link } from "@tanstack/react-router";
import { BatteryCharging, Filter, MapPin, Search, SlidersHorizontal, Sparkles } from "lucide-react";
import { useState } from "react";
import { AppShell, DemoBadge } from "@/components/circular-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export const Route=createFileRoute("/marketplace")({head:()=>({meta:[{title:"Marketplace B2B — CircularIA"},{name:"description",content:"Encontre baterias e componentes para novos ciclos de valor."},{property:"og:title",content:"Marketplace B2B — CircularIA"},{property:"og:description",content:"Ativos disponíveis para segunda vida, remanufatura e reciclagem."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Marketplace});
const items=[{name:"Pack LFP",cap:"48 kWh",city:"Região Sudeste",soh:"76%",qty:"8 unidades",use:"Armazenamento estacionário"},{name:"Módulos NMC",cap:"5 kWh",city:"Região Sudeste",soh:"82%",qty:"24 unidades",use:"Aplicações industriais"},{name:"Pack NCA",cap:"65 kWh",city:"Região Sul",soh:"58%",qty:"3 unidades",use:"Remanufatura"},{name:"Módulos LFP",cap:"7,2 kWh",city:"Região Sudeste",soh:"69%",qty:"16 unidades",use:"Backup energético"}];
function Marketplace(){const [interest,setInterest]=useState<string[]>([]);return <AppShell title="Marketplace B2B" subtitle="Explore ativos disponíveis e solicite um match com base nas necessidades da sua empresa."><div className="grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="rounded-lg border border-border bg-card p-4"><h2 className="flex items-center gap-2 font-bold"><SlidersHorizontal className="size-4"/>Filtros</h2><div className="mt-5 space-y-4">{["Tipo de bateria","Química","SoH","Estado","Quantidade","Aplicação potencial"].map(f=><label key={f}><span className="mb-1.5 block text-xs font-semibold">{f}</span><select className="h-9 w-full rounded-md border border-input bg-background px-2 text-xs"><option>Todos</option><option>LFP</option><option>NMC</option><option>São Paulo</option></select></label>)}</div><Button variant="outline" className="mt-5 w-full"><Filter/>Aplicar filtros</Button></aside><div><div className="mb-5 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar ativo, química ou cidade"/></div><DemoBadge/></div><div className="grid gap-4 xl:grid-cols-2">{items.map(item=><article key={item.name} className="rounded-lg border border-border bg-card p-5"><div className="flex justify-between"><span className="rounded-md bg-accent p-2 text-primary"><BatteryCharging/></span><DemoBadge/></div><h2 className="mt-5 text-xl font-bold">{item.name} <span className="text-primary">— {item.cap}</span></h2><p className="mt-2 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-4"/>{item.city} · localização aproximada</p><p className="mt-2 text-xs font-semibold text-primary">Empresa ofertante verificada · identidade protegida</p><dl className="mt-5 grid grid-cols-2 gap-4 border-y border-border py-4 text-sm"><div><dt className="text-xs text-muted-foreground">SoH informado</dt><dd className="font-bold">{item.soh}</dd></div><div><dt className="text-xs text-muted-foreground">Disponibilidade</dt><dd className="font-bold">{item.qty}</dd></div><div className="col-span-2"><dt className="text-xs text-muted-foreground">Aplicação potencial</dt><dd className="font-bold">{item.use}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" variant="outline" asChild><Link to="/oportunidade" search={{ match: "#1842" }}>Ver detalhes</Link></Button><Button size="sm" variant="outline" onClick={()=>setInterest(s=>[...s,item.name])}>{interest.includes(item.name)?"Interesse registrado":"Demonstrar interesse"}</Button><Button size="sm" asChild><Link to="/matches">Solicitar Match<Sparkles/></Link></Button></div></article>)}</div></div></div></AppShell>}
